### ISSUE TITLE
Could not wrap any native library from list

### ISSUE THREAD

**Issue by GeoffreyPlitt** [positively4th/fluid4node#1]
I'm very interested to play with this!

Raspberry Pi, which is Raspbian Jessie, and running NodeJS 8.something.

I get error "Could not wrap any native library from list: ' + libs.join(', '), res.failedLibs);"

**Comment by GeoffreyPlitt** [comment]
Maybe I need an arm-compiled libfluidsynth.so lib?

**Comment by jwulf** [comment]
Yes, on my dietpi machine, I did: `apt install libfluidsynth1`, then copied the file `/usr/lib/arm-linux-gnueabihf/libfluidsynth.so.1` into `node_modules/fluid4node/lib/linux`. 

That got rid of this error. Now I have another error related to the JACK Audio server, when I run the `test.js` file.

I'll create a pull request for the arm version of the library. My board is a Rpi Zero, so it's ARM v6.

**Comment by jwulf** [comment]
Actually, you can do it without a PR. The default export of the module takes a `spec` with arguments. I fixed my JACK error by specifying `alsa` as the driver. You can also pass in the path to the lib to wrap, as well as a soundFont to load.

Like this:

```
const f4n = require('fluid4node')({
    libs: ['/usr/lib/arm-linux-gnueabihf/libfluidsynth.so.1'],
    drivers: ['alsa'],
    soundFonts: ['/root/sf2/Harmonium.sf2']
});
```
